-- Add REVISIONS status to shot_status enum
-- Revision loop: CLIENT_REVIEW → REVISIONS → IN_PROGRESS → INTERNAL_REVIEW → CLIENT_REVIEW
ALTER TYPE shot_status ADD VALUE 'REVISIONS' AFTER 'CLIENT_REVIEW';
